### ISSUE TITLE
Too many errors from stdin

### ISSUE THREAD

**Issue by AnLAdmin** [geophile/marcel#10]
Ubuntu: 18.04.4
Python3: 3.6.9
Marcel: 0.12.2

Starting nano is not possible (with or without file argument). -> Results in "Too many errors from stdin"
Runs in bash.

**Comment by AnLAdmin** [comment]
Ups, i overread this in your answer to issue #6.
The workarround is:
bash -i nano

But I hope you will make this possible.

**Comment by geophile** [comment]
You can fix this yourself. The executables started "interactively" (with the bash -i flag) are identified by the environment variable INTERACTIVE_EXECUTABLES. It's a list of strings. To append to this list, you can do this at the marcel prompt:

(INTERACTIVE_EXECUTABLES.append('nano'))

Or, to make the change permanent, add that line to your .marcel.py file, which configures marcel. Note that when you change .marcel.py, it is automatically re-executed, (so you can edit the file and have the change take effect immediately).

**Comment by geophile** [comment]
Correction: In the .marcel.py file it would be:

INTERACTIVE_EXECUTABLES.append('nano')

(Leaving out the outermost parens)

**Comment by geophile** [comment]
I just checked in an improvement here, v0.12.4. I moved the definition of INTERACTIVE_EXECUTABLES into .marcel.py. If you already have run marcel, you will need to put it there yourself, since you already have a .marcel.py file.

INTERACTIVE_EXECUTABLES = [
    'emacs',
    'less',
    'man',
    'more',
    'psql',
    'top',
    'vi',
    'vim'
]

(And add nano if you'd like.)

And if you have never run marcel, you will get a .marcel.py file the first time you run marcel, with INTERACTIVE_EXECUTABLES defined as above.

**Comment by AnLAdmin** [comment]
Thanks for the answer.
Out of curiosity, why don't you set this as default for all apps?

**Comment by geophile** [comment]
Because some executables use over stdin and stdout for interaction with the
user, like nano does, and others do not. For example, suppose I want to use
sed to operate on a marcel stream, e.g.

M 0.12.4 jao@cheese ~$ gen 5 | (x: (x, x)) | sed s/2/TWO/g
(0, 0)
(1, 1)
(TWO, TWO)
(3, 3)
(4, 4)

If I include sed in INTERACTIVE_EXERCUTABLES, then the tuples generated by
gen don't reach sed, and nothing happens. Try it and see.

I decided that the default should be non-interactive, allowing host OS
executables to participate in marcel pipes.

**Comment by AnLAdmin** [comment]
Is it planned to implement an automatic solution? 😉

**Comment by geophile** [comment]
Running interactive host OS commands is a problem area. I need to learn
more about process interactions with stdin, stdout and stderr in order to
make improvements. It is a goal to make INTERACTIVE_EXECUTABLES
unnecessary, and to improve the operation of commands like "less", for
example.

**Comment by Tubbles** [comment]
Just chiming in, I think some kind of escaping could make sense for starting applications in interactive mode instead of normal mode, eg. `[vim]` or `$vim`. What do you think?

**Comment by geophile** [comment]
I'm open to the idea, but I don't like it. But I also don't like having to identify the interactive executables in the environment. I think there is probably a way to identify interactive executables reliably and automatically, and that it is my ignorance in the way. (I'd be happy to work with someone who is interested and has more expertise in this area.)
