### ISSUE TITLE
Needs Nix(OS) package

### ISSUE THREAD

**Issue by elmarsto** [geophile/marcel#16]
AFAICT there's currently no package for this lovely little shell in Nix (and therefore, NixOS.) 

Generally making .nix packages from Python packages is fairly trivial, so I'm going to try later this week.

If anyone wants to beat me to it, go ahead. :D

**Comment by geophile** [comment]
Hi, you must be 1attice from the github discussion. Please go ahead, this is an extremely low volume repository. Extremely.

**Comment by elmarsto** [comment]
Yes, that's correct. Thanks! Can't justify it at work, but I'll have free time this weekend

**Comment by arcuru** [comment]
I've made a packaging request in the nixpkgs repo: https://github.com/NixOS/nixpkgs/issues/263995

**Comment by elmarsto** [comment]
Sorry this hasn't happened yet; I've been busy.

**Comment by geophile** [comment]
I've been waiting for some interest in marcel for years, so a few days more can't hurt.

**Comment by KUD-00** [comment]
Marcel uses hard-coded '/bin/bash' and it can't be found on NixOS. Then I intended to use 'env bash' but it seems not working. I'm not familiar with marcel so I want some help.

**Comment by geophile** [comment]
I'm not familiar with NixOS. How is it located there?

**Comment by geophile** [comment]
> Marcel uses hard-coded '/bin/bash' and it can't be found on NixOS. Then I intended to use 'env bash' but it seems not working. I'm not familiar with marcel so I want some help.

Do you mean that you tried replacing '/bin/bash' wiith 'env bash' in marcel/op/bash.py? That wouldn't work. The thing to do would be to locate bash on marcel startup (e.g. by running 'env bash') and recording the location.

So the question is, how do you locate bash in NixOS? Does 'env bash' work?

**Comment by elmarsto** [comment]
https://discourse.nixos.org/t/shebang-locations/28992
https://nix.dev/tutorials/first-steps/reproducible-scripts

**Comment by geophile** [comment]
There are two kinds of references to /bin/bash in marcel:

1) In two scripts: testall, and marcel. testall is a script that runs
all unit tests. marcel is the top-level script starting marcel. Both
of these scripts start like this:

    #!/bin/bash

2) In two of marcel's operators, edit and bash. The edit operator runs
your favorite editor (specified by the EDITOR environment variable) on
some command in the command history. The bash operator runs a bash
script, taking care of streaming via pipes between marcel and the command.
In both of these cases, the Python method subprocess.Popen is
called to execute a command. Here is the invocation from edit.py:

        process = subprocess.Popen(edit_command,
                                   shell=True,
                                   executable='/bin/bash',
                                   universal_newlines=True)

From the NixOS documentation you provided, it looks to me like fixing
the scripts is as simple as replacing this:

    #!/bin/bash

with this:

    #!/usr/bin/env bash

As for the edit and bash operators, what would you recommend? If I ran
"which bash" on marcel startup to determine the location of the OSs
bash executable, and then passed that location to subprocess.Popen,
would that work better with NixOS?

I do all my work on one computer, a Pop OS laptop. I'm happy to try
out NixOS, perhaps as an AWS instance. Can you point me in the right
direction for getting started with NixOS quickly, so that I can play
with marcel in a NixOS environment?

**Comment by KUD-00** [comment]
To play marcel on NixOS, you can clone this repo that i forked from nixpkgs: [nixpkgs](https://github.com/KUD-00/nixpkgs)

Then execute `nix-build -A marcel`, if the build is okay, execute `nix-shell -A marcel` (this will let you in a environment that contains marcel dependencies), then execute `./result/bin/marcel`

The source code(default.nix) is in `pkgs/development/python-module/marcel`, contains a default.nix and a patch that make "bin/bash" to `/run/current-system/sw/bin/bash`, which is a folder that managed by nixos and contains all command.

Now it use latest marcel commit as source, and i found that it may be inappropriate to put it under development/python-module. If marcel build from this works well, maybe it's better to change it to 1.7.0 and put it under other folder (instead of python-module)

I'm new to nixpkgs, I may make a lot of mistakes.

**Comment by arcuru** [comment]
>  Can you point me in the right direction for getting started with NixOS quickly, so that I can play with marcel in a NixOS environment?

Nix is a package manager that is available for most distros, though the install process may be annoying. Nix the package manager uses nixpkgs the package repository. Nixos is a linux distro that uses Nix as it's package manager. There's info about installing it here, though there may be more specific instructions for your distro: https://nixos.org/download

What I'm saying is that you can use and develop with Nix/nixpkgs on your laptop if you want, or install it on a different distro on a cloud box. NixOS is not well supported on any cloud providers AFAIK, I don't know if any of them provide a NixOS image to use without jumping through hoops.

> I'm new to nixpkgs, I may make a lot of mistakes.

I am familiar with Nix/Nixpkgs, but not with python so I can't fix the problems with packaging here. I would strongly recommend that you open a PR in the nixpkgs repo, and ask for any help in the matrix chatroom, specifically https://matrix.to/#/#dev:nixos.org. They can probably help sort out any issues relatively quickly. 

Usually they are pretty helpful and friendly :)

**Comment by geophile** [comment]
How do we get this work going? 

@KUD-00 has forked nixpkgs and started making some changes to marcel. Those need some work, in order to be checked back in to the marcel repository. Also, they don't address the marcel and testall scripts mentioned in my previous comment.  (BTW, there is no point in fixing those "experiment" bits of code. Those should probably not even be there, they are just a playground for me to try out things. I'll remove them in a near-future commit.)

It sounds like @arcuru is more familiar with nixpkgs. 

I'd like to suggest the following: @KUD-00 continues with his fork of nixpkgs, working with @arcuru on the nix parts, and me on the marcel parts. Does this make sense?

**Comment by elmarsto** [comment]
This article is a good introduction to Nix, @geophile

**Comment by KUD-00** [comment]
I opened a [PR](https://github.com/NixOS/nixpkgs/pull/267461) to nixpkgs. Not sure if it will be accepted, but I will try my best.

The problems I encountered in packaging marcel:
- **hard-coded bash**: As you said `ran "which bash" on marcel startup to determine the location of the OSs bash executable, and then passed that location to subprocess.Popen, would that work better with NixOS?` I think it will work better with NixOS. No need for patches.
- **tests**: It seems that tests need to read/write `$HOME/.local/marcel` for some reason. When installing nix do all things in a sandbox so it will cause "permission denied". As a result,  I disabled the tests ( it seems a common thing in nix, though it's not good ).
- **version**: I saw that marcel on pypi is already at 0.19.0, but source on pypi only contains whl. Nix needs tarball. Maybe there will be more releases on GitHub?

None of them is easy to deal with. But without dealing them, NixOS can run marcel well. So maybe it's not worth editing just for NixOS users. 

Actually I didn't use marcel before, I  saw the package request in nixpkgs so I want to have a try. But after packaging it i found its an amazing shell (with python in shell! wow!). Thank you for creating this amazing cute shell.

**Comment by geophile** [comment]
Thank you! 

hard-coded bash: I would like to improve marcel so that it runs on a wider variety of platforms, so I will fix the hard-coded /bin/bash invocations. This will have benefits beyond nix.

tests: What is going on here is that marcel creates $HOME/.local/share/marcel and $HOME/.config/marcel if they don't exist. (You meant $HOME/.local/share/marcel, not $HOME/.local/marcel, right?)  These directories store the command history, the startup script, and will store more things in the near future. I can see two possible fixes here. One is to create those directories as part of installation. Do you think that would work better with nix?  (Of course, that doesn't work so well if I install marcel as root, and then run it as myself.)  Another possibility is to have tests use locations other than $HOME/{.local,.config}. But of course, the more that testing differs from real usage, the greater the opportunity for bugs. Disabling tests seems like a real problem.

version: Tell me more about what nix needs in a tarball. I'd be happy to provide what's needed.

**Comment by geophile** [comment]
I have a nix bootstrapping sort of question. 

I see a way to avoid hardwiring "/bin/bash" in marcel python code, and in scripts. I would run "which bash" at installation time, record that location in a file (e.g. under $HOME/.config/marcel), and then use that info in the marcel runtime (for the bash and edit operators), and also to generate the testall and marcel scripts, (the shebang lines).

Here's the problem: How do I write the script that runs "which bash"?  I could do this:

    #!/bin/bash
    which bash > file_remembering_the_bash_location

However the very first line itself hardcodes /bin/bash!

So how do I discover the bash location without needing to know it in the first place? I'd love to find a solution that works for nix but also more generally.

**Comment by geophile** [comment]
OK, I have an idea. Here is a little Python program to discover the path to bash. It relies on a shell, but *Python* has to get it right. If Python is running correctly on nix, then I suspect this will work in marcel. Can someone running nix tell me what happens when you run this:

    import subprocess

    p = subprocess.run('which bash', shell=True, capture_output=True)
    print(p.stdout.strip().decode('UTF-8'))

Thanks.

**Comment by arcuru** [comment]
I ran that on NixOS, and that script does output the correct path to bash on NixOS. The subprocess.popen docs recommend using `shutil.which()` if you don't know the path to the executable: https://docs.python.org/3/library/subprocess.html#popen-constructor

@geophile Your script does exactly the same thing I'd assume, but the following works as well:

```python
import shutil

print(shutil.which('bash'))
```

Thanks @KUD-00 for starting the PR! Looks like you're already getting some good feedback.

**Comment by arcuru** [comment]
Also the shebang lines in scripts (and the other hardcoded links to binaries) pretty often need to be patched to run under nix. Cleaning these up as part of the package in Nix is a very normal part of the packaging process.

You'll notice that kud's PR doesn't patch any of the shebang lines, that's because the nix packaging by default runs a script [`patchShebangs`](https://github.com/NixOS/nixpkgs/blob/ca156a66b75999153d746f57a11a19222fd5cdfb/pkgs/build-support/setup-hooks/patch-shebangs.sh) that cleans them up. A similar substitute just isn't run on the python code by default. So as far as Nix is concerned, you can write the shebang lines in scripts however you want.

For general use, I'm pretty sure that `#!/usr/bin/env bash` is the most portable shebang for bash. NixOS even keeps that `env` binary available there for ease of use.

**Comment by geophile** [comment]
Thanks, @arcuru, shutil.which is much better. That works for me, as does the shebang you suggested.

One more thing to consider: The script for remote and multiprocess execution, farcel.py, uses #!/usr/bin/python3. Should I change that to #!/usr/bin/env python3?

**Comment by arcuru** [comment]
Yea, I think it's probably also better to use /usr/bin/env to find python3 as well. It'll ultimately cause fewer issues.

**Comment by geophile** [comment]
I've made all those changes and they work for me. Later today I will check in v0.20.0. This will have the changes we've been discussing here, as well as a lot of refactoring that will support some major new features coming. 

I'll be interested to see how well these bash-related changes work on nix.

**Comment by geophile** [comment]
0.20.0 is available.

**Comment by KUD-00** [comment]
Now marcel is available in nixpkgs ( although it may still takes some time to be available in nixos-unstable or stable channel ), I think this issue can be closed. 

Any further issue related to packaging for nixos may should be open in nixpkgs repo.
