### ISSUE TITLE
Root path `/` is converted to a list of root folders

### ISSUE THREAD

**Issue by cfinnberg** [geophile/marcel#30]
Quite a simple one, but `cd /` fails with `Too many paths`.
Related to the same bug, `ls /` lists all root folders contents.

Given how op.Filenames.normalize method is built, I would just return `[path]` if path is root folder, but I'm not sure how do you prefer to handle it.

Also, can I ask what's your policy on releases? The last release is 0.22.2

**Comment by geophile** [comment]
Thanks for finding this. I just checked in something very much like what you suggested. In setting up the glob search, I forgot the / special case, so the glob pattern was an empty string, and hilarity ensued.

My release policy has been wildly informal, basically when I felt like it, usually in connection with major new features or visible changes. I need to get more formal, at least for dot releases, since there is now migration support, (not that migration should often be necessary).

I will commit to doing a new major release when there is some visible change. I'll bump that number momentarily since it's been a while, and there have been visible changes since the last release.

**Comment by geophile** [comment]
I'll let you confirm that the cd / bug is fixed. If you agree, please close this issue.

**Comment by cfinnberg** [comment]
Seems good to me. Thanks!
